### ISSUE TITLE
Protocol error (Fetch.continueRequest): Target closed.

### ISSUE THREAD

**Issue by hamza172** [zytedata/zyte-smartproxy-puppeteer#7]
Hello, 
I am getting this error when i try to run the sample code

`
F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });                               
Error: Protocol error (Fetch.continueRequest): Target closed.
    at F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)
    at ZyteSmartProxyPuppeteer._continueRequest (F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\src\index.js:189:30)
    at F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\src\index.js:102:47
    at F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (F:\Scrapping\node_modules\zyte-smartproxy-puppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)`

I have read that this error occurred in a specific version of Puppeteer. Is that the reason or i am doing something wrong?

**Comment by hamza172** [comment]
Getting this error on the sample code pasted in description as well

**Comment by geronsv** [comment]
Hi @hamza172
Thanks for the feedback!
Could you help us reproduce the issue?
Are you using the exact sample code from the [QuickStart](https://github.com/zytedata/zyte-smartproxy-puppeteer#quickstart)?
What is the node version you are using?
Could you create a new directory for your project and reinstall `zyte-smartproxy-puppeteer`?
```
npm install zyte-smartproxy-puppeteer
```
